name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [win-x86,win-x64,win-arm64]
        include:
          - target: win-x86
            platform: win
            architecture: x86
          - target: win-x64
            platform: win
            architecture: x64
          - target: win-arm64
            platform: win
            architecture: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: "8.0.x"

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build utilities
        shell: pwsh
        run: |
          msbuild /m /t:restore,img2ffu:publish /p:Platform=${{ matrix.architecture }} /p:RuntimeIdentifier=${{ matrix.platform }}-${{ matrix.architecture }} /p:PublishDir=${{ github.workspace }}/artifacts/${{ matrix.platform }}-${{ matrix.architecture }} /p:PublishSingleFile=true /p:PublishTrimmed=false /p:Configuration=Release Img2Ffu.sln

      - name: Create PDB Output Directory
        shell: pwsh
        run: |
          mkdir ${{ github.workspace }}\artifacts\${{ matrix.platform }}-${{ matrix.architecture }}\PDBs

      - name: Move PDBs
        shell: pwsh
        run: |
          move ${{ github.workspace }}\artifacts\${{ matrix.platform }}-${{ matrix.architecture }}\*.pdb ${{ github.workspace }}\artifacts\${{ matrix.platform }}-${{ matrix.architecture }}\PDBs\

      - name: Upload artifact (Binaries)
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ matrix.platform }}-${{ matrix.architecture }}-binaries
          path: ${{ github.workspace }}/artifacts/${{ matrix.platform }}-${{ matrix.architecture }}

      - name: Upload artifact (Symbols)
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ matrix.platform }}-${{ matrix.architecture }}-symbols
          path: ${{ github.workspace }}/artifacts/${{ matrix.platform }}-${{ matrix.architecture }}\PDBs

      - name: Delete old pre-release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: pre-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
        workflow: <workflow_name>
        name: win-arm64-binaries, win-x64-binaries, win-x86-binaries

      - name: Create new release
      uses: ncipollo/release-action@v1
      with:
        name: pre-release
        body: Bleeding-edge build
        artifacts: win-arm64-binaries, win-x64-binaries, win-x86-binaries
        tag: pre-release
        token: ${{ secrets.GITHUB_TOKEN }}
